# Generated by Django 5.0.1 on 2024-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_activation_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activation_token_expire',
            new_name='confirmation_code_expire',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activation_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
