# Generated by Django 5.0 on 2024-02-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
